version: '3.9'

services:
  postgres:
    image: postgres:16.1-alpine
    ports:
      - 5432:5432
    volumes:
      - C:\home\database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=acedix_db
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"